apiVersion: v1
kind: Service 
metadata: 
  name: my-svc
  labels: 
    app: nginx-app
spec: 
  type: NodePort
  ports:
    - name: http 
      port: 80
      targetPort: 80
  selector:
    app: nginx-app