apiVersion: apps/v1
kind: Deployment
metadata: 
  name: test-deploy
  labels: 
    app: nginx-app
spec: 
  replicas: 5
  template: 
    metadata:
      name: custom-deploy
      labels:
        app: nginx-app
    spec: 
      containers:
      - name: nginx-deploy
        image: nginx 
  selector: 
    matchLabels:
      app: nginx-app