## A Job creates one or more Pods and will continue to retry execution of the Pods until a specified number of them successfully terminate.
## A simple case is to create one Job object in order to reliably run one Pod to completion.
## Deleting a Job will clean up the Pods it created. Suspending a Job will delete its active Pods until the Job is resumed again.
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
