apiVersion: v1
kind: Pod
metadata:
  name: pod-resource
spec:
  containers:
  - name: pod-resource
    image: ubuntu
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "500m"
