apiVersion: apps/v1
kind: ReplicaSet
metadata: 
 name: my-rs
 labels:
   app: nginx-app
spec:
 replicas: 3
 selector:
   matchLabels:
     app: nginx-app
 template:
   metadata:
     name: my-pod
     labels: 
       app: nginx-app
   spec: 
    containers:
      - name: nginx
        image: nginx 
