apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app
  name: svc-nginx
spec:
  ports:
  - name: nginx
    port: 80
    targetPort: nginx
    nodePort: 30008
  selector:
    app: nginx-app
  type: NodePort
