apiVersion: v1
kind: Pod
metadata:
  name: admin-ui
  namespace: default
  labels:
    app: call-book
spec:
  containers:
  - name: admin-ui
    image: us-central1-docker.pkg.dev/optimal-harbor-386603/bhargava/admin-ui 
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - name: admin-ui-port
      containerPort: 3000
